### DISCUSSION TITLE
iiab Curl install issue

### DISCUSSION THREAD

**Discussion by Mum-O-Killowe** [iiab/iiab#3809] [Q&A]
I did a fresh Raspi OS 64 bit install on a new Pi 5 and then did the single line command install of Internet in a box.    I can't access box.lan or box.lan\admin.    I have the Pi on my home wireless network.   I can SSH into it and VPN is working.   I have ran sudo iiab repeatedly trying to ensure all files are installed and working.    I can't get to the console to actually run iiab however.    I'm pretty new to all this.    Can someone kick my ignorant arse down the road of enlightenment here?   What am I missing?

Thanks

**Comment by holta** [comment]
@Mum-O-Killowe

1. Can you run `sudo iiab-diagnostics` and then hit enter, to generate a URL?  Can you send us this URL to help us diagnose?

2. Either way, can you reply with photo(s) or screenshot(s) to explain what's most frustrating?

Thanks!

**Reply by Mum-O-Killowe** [reply]
https://paste.centos.org/view/a0b4a980  

![image](https://github.com/user-attachments/assets/57e97be2-341c-4d58-975a-e689fcd067e7)

Just not sure how to actually launch the console.    To be clear, I am not using an ethernet cable.   I did everything over wifi and the Pi5 is set up with my home wifi network.   I do not see an Internet in a Box wireless network.

**Comment by holta** [comment]
@Mum-O-Killowe thanks for your `iiab-diagnostics` & screenshot!  Just 3 quick observations for now:

1. Your IIAB installed 24 of 25 apps correctly (see lines 834-858 of https://paste.centos.org/view/a0b4a980 from your /etc/iiab/iiab_state.yml) but appears to have failed to install the 25th app (Calibre-Web).   Let me ask @deldesir to try to explain why Calibre-Web failed to install for you, as your iiab-diagnostics shows on Lines 1954-2028 of https://paste.centos.org/view/a0b4a980

2. While not advisable for newcomers, it looks like you tried to install a LARGE-sized IIAB (which almost completed, as mentioned above) and then you copied the [MEDIUM-sized IIAB template](https://github.com/iiab/iiab/blob/master/vars/local_vars_medium.yml) onto [/etc/iiab/local_vars.yml](https://wiki.iiab.io/go/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it?) — **that will definitely not work as IIAB does not support removal of apps!**  ONE OF MANY EXAMPLES: It's _never allowed_ to revert variables in `/etc/iiab/local_vars.yml` from...

   ```
   moodle_install: True
   moodle_enabled: True
   ```

   ...to...

   ```
   moodle_install: False
   moodle_enabled: False
   ```

   ...as you've accidentally done!  See Lines 685 and 686 of https://paste.centos.org/view/a0b4a980 :smile:

3. It appears you accidentally tried to install the 3 PRs / pull requests below (while possibly harmless, that's essentially dangerous if you not doing it for a good reason, so please don't do that in future!)

   - PR iiab/iiab-admin-console#361
   - PR #2604 
   - PR #2607

**Comment by holta** [comment]
> ask @deldesir to try to explain why Calibre-Web failed to install for you, as your iiab-diagnostics shows on Lines 1954-2028 of https://paste.centos.org/view/a0b4a980

Question for @deldesir:

- IIAB Calibre-Web currently installs on Debian 12 and Ubuntu 24.10 using [omg.yml](https://github.com/iiab/calibre-web/wiki#wrench-installation) ✅ 
- Is there any chance some IIAB Calibre-Web dependency (apt, or pipx, or similar) is broadly failing to install on Raspberry Pi OS at the moment? ⚠️

**Reply by deldesir** [reply]
Might be related to HTTP/2 stream handling

https://lore.kernel.org/all/4454d8e1dab565118a316409d653844bbbfacfc7@hardeman.nu/T/

https://stackoverflow.com/questions/59282476/error-rpc-failed-curl-92-http-2-stream-0-was-not-closed-cleanly-protocol-erro

Suggested change in `/opt/iiab/iiab/roles/calibre-web/tasks/install.yml` after version in line 79

Add:

```
config:
      http.version: "HTTP/1.1"
```

The task will look like 

```
- name: git clone Calibre-Web ({{ calibreweb_version }}) from {{ calibreweb_repo_url }} to {{ calibreweb_venv_path }} (~122 MB initially, ~191+ or ~203+ MB later) -- if {{ calibreweb_venv_path }} doesn't exist
  git:
    repo: "{{ calibreweb_repo_url }}"    # e.g. https://github.com/iiab/calibre-web or https://github.com/janeczku/calibre-web
    dest: "{{ calibreweb_venv_path }}"
    version: "{{ calibreweb_version }}"    # e.g. master, 0.6.22
    config:
      http.version: "HTTP/1.1"
  when: not calibreweb_venv.stat.exists
```
