### ISSUE TITLE
Remove Ansible's pink/red warnings. Prep for Ansible 2.8/2.9 and 2.11 deprecations.

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1130]
Not all of Ansible's pink/red warnings are removable &mdash; indicating too many callouts to bash/sudo etc &mdash; but most will be!

Ref: #1100 (Migrate to Ansible 2.7 on "2018-10-04")

**Comment by holta** [comment]
See PR #746 "Speedup by squashing package installs in ansible.cfg (condenses loop)" which is related &mdash; that PR was a real lifesaver (saving ~20 min on each RPi install, by avoiding dozens of unnec calls to "apt update") as contributed by @jvonau in April 2018.

**Comment by arky** [comment]
It seems this is a trivial fix. You shouldn't use 'with_items' looping in package module anymore.

Use 'name:' instead of 'with_items' looping: 

```
package:
    name: "{{ item }}"
    state: present
  with_items:
    - openvpn
    - nmap
```

```
package:
     name:
       - openvpn
       - nmap
      state: present
 
```
