### ISSUE TITLE
install stage arithmetic could be more flexible

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#2371]
When an aggregate role finishes it sets last stage to its stage. It could only do this if its stage is greater than the current last stage. This would allow an earlier stage to be rerun without requiring all subsequent stages to be rerun.

For example:

```
- name: Recording STAGE 2 HAS COMPLETED ==========================
  lineinfile:
    path: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=2'
  when: {{ iiab_stage }} < 2

```
