### ISSUE TITLE
references to admin console

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#2560]
I don't understand 4-server-options/tasks/main.yml 59ff:
```
# 2020-02-17: what was roles/homepage lives in roles/www_options.  Eventually
# softcoding of iiab_home_url should happen everywhere (incl Admin Console) for
# more field options, e.g. changing /library/www/html/home even when offline...
```
Is this still needed, nginx/tasks/install.yml 19ff?

```
- name: Add user '{{ apache_user }}' to shadow group, so it can authenticate Admin Console
  user:
    name: "{{ apache_user }}"    # www-data or apache, per /opt/iiab/iiab/vars/<OS>.yml
    groups: shadow

```
captiveportal/tasks/enable-or-disable.yml and elsewhere. If desired admin console can install uwsgi: it already installs the config files for admin console. (btw it only uses 1 child process, though with 4 threads)

```
# 2020-01-22: Package 'uwsgi' is installed by nginx/tasks/install.yml for
# Captive Portal (responds to browsers trying to detect a Captive Portal) and
# also for Admin Console.

# IIAB makes the 'uwsgi' service mandatory for now (see Line 45) but this could
# perhaps be auto-disabled in future (or never installed?)  e.g. if Captive
# Portal + Admin Console are both unneeded...and impact of uWSGI is too high ?

- name: Stop 'uwsgi' systemd service (may include 3 child processes for Captive Portal, and 3 child processes for Admin Console)
  systemd:
    name: uwsgi
    state: stopped

```
