### ISSUE TITLE
Sugarizer won't start due to "Illegal instruction /usr/bin/mongod --repair --dbpath /library/dbdata/mongodb" [also reveals flaws in /etc/mongod.conf, mongodb.service & iiab-mongodb-repair-if-no-lock]

### ISSUE THREAD

**Issue by holta** [iiab/iiab#3236]
Thanks to @nzola who uncovered this:

```
1958 Jun  6 13:40:18 raspberrypi iiab-mongodb-repair-if-no-lock[76019]: /usr/bin/iiab-mongodb-repair-if-no-lock: line 7: 76020 Illegal instruction     /usr/bin/mongod --repair --dbpath /library/dbdata/mongodb
1959 Jun  6 13:40:18 raspberrypi systemd[1]: mongodb.service: Control process exited, code=exited, status=132/n/a
1960 Jun  6 13:40:18 raspberrypi systemd[1]: mongodb.service: Failed with result 'exit-code'.
1961 Jun  6 13:40:18 raspberrypi systemd[1]: Failed to start High-performance, schema-free document-oriented database.
```

From http://sprunge.us/LbT5zf?en on Raspberry Pi OS on RPi 4, but I assume this applies to all OS's.

Likely as a result of MongoDB 5.x (released 11 months ago) which presumably no longer supports the legacy syntax / command used by [iiab-mongodb-repair-if-no-lock](https://github.com/iiab/iiab/blob/master/roles/mongodb/templates/iiab-mongodb-repair-if-no-lock.j2) :

- PR #3214

In any case, with MongoDB 6.0 now imminent, it's time for IIAB to catch up.  I'll investigate.

**Comment by holta** [comment]
Just FYI IIAB's 241-line [template for /etc/mongod.conf](https://github.com/iiab/iiab/blob/master/roles/mongodb/templates/mongod.conf.j2) (IIAB currently used this for 32-bit Raspberry Pi OS only) appears archaic to the point where it's become highly misleading.

Whereas on 64-bit OS's, IIAB currently uses MongoDB 5.0's own default 42-line `/etc/mongod.conf` _which uses the wrong DB below i.e. `/var/lib/mongodb` instead of `/library/dbdata/mongodb` !_  (But still we might consider this as a basis for IIAB's future template?)

```
# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  dbPath: /var/lib/mongodb
  journal:
    enabled: true
#  engine:
#  wiredTiger:

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1


# how the process runs
processManagement:
  timeZoneInfo: /usr/share/zoneinfo

#security:

#operationProfiling:

#replication:

#sharding:

## Enterprise-Only Options:

#auditLog:

#snmp:
```
