### ISSUE TITLE
This protects the user when first installing, but does not protect later changes done by admin-console

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#3242]
> > This protects the user when first installing, but does not protect later changes done by admin-console
> 
> Yes.
> 
> This was done on purpose so implementers who really want to can try again 10/20/30 days later — if they really want to try installing apps/services.
> 
> Using either `sudo ./runrole <app>` or Admin Console.

This 'workaround' has effectively broken the preset functionality other than for the medical one.
>ubuntu@exclusive-limpkin:/opt/iiab/iiab-admin-console$ grep next roles/cmdsrv/files/presets/*/vars.yml
roles/cmdsrv/files/presets/en-school-256-base/vars.yml:nextcloud_install: True
roles/cmdsrv/files/presets/en-school-256-base/vars.yml:nextcloud_enabled: True
roles/cmdsrv/files/presets/en-school/vars.yml:nextcloud_install: True
roles/cmdsrv/files/presets/en-school/vars.yml:nextcloud_enabled: True
roles/cmdsrv/files/presets/es-school/vars.yml:nextcloud_install: True
roles/cmdsrv/files/presets/es-school/vars.yml:nextcloud_enabled: True
roles/cmdsrv/files/presets/fr-school/vars.yml:nextcloud_install: True
roles/cmdsrv/files/presets/fr-school/vars.yml:nextcloud_enabled: True
 
>ubuntu@exclusive-limpkin:/opt/iiab/iiab-admin-console$ grep sugar roles/cmdsrv/files/presets/*/vars.yml
roles/cmdsrv/files/presets/en-school/vars.yml:sugarizer_install: True
roles/cmdsrv/files/presets/en-school/vars.yml:sugarizer_enabled: True
roles/cmdsrv/files/presets/es-school/vars.yml:sugarizer_install: True
roles/cmdsrv/files/presets/es-school/vars.yml:sugarizer_enabled: True

And sets up the user for a fail should the user attempt to use ICO with a medium or larger install without even changing anything.

![Screenshot from 2022-05-01 23-56-16](https://user-images.githubusercontent.com/5579710/166186244-8190d60c-b654-4108-a08f-0d5c1be62115.png)

ubuntu@exclusive-limpkin:/opt/iiab/iiab$ `cat adm-run-roles-tmp.yml`
```
---
- hosts: all
  become: yes

  vars_files:
  - vars/default_vars.yml
  - vars/{{ ansible_local.local_facts.os_ver }}.yml
  - /etc/iiab/local_vars.yml
  - /etc/iiab/iiab_state.yml

  roles:
    - { role: 0-init }
    - { role: kolibri }
    - { role: nextcloud }
    - { role: sugarizer }
    - { role: network }
```

_Originally posted by @jvonau in https://github.com/iiab/iiab/issues/3189#issuecomment-1114501001_
