### ISSUE TITLE
Think this might be an admin-console issue, the tick box uncheck should of only written 'enabled False' and left as 'install True' in local_vars.yml

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#3243]
Going back to un-tick kolibri, save, ico.

![Screenshot from 2022-05-02 00-15-49](https://user-images.githubusercontent.com/5579710/166187700-f63853ce-8c63-4394-8b39-8e9926e2407c.png)

2022-05-02 00:15:21,252 p=92605 u=root n=ansible | failed: [127.0.0.1] (item=kolibri) => {"ansible_loop_var": "item", "assertion": "kolibri_install or kolibri_installed is undefined", "changed": false, "evaluated_to": false, "item": "kolibri", "msg": "DISALLOWED: 'kolibri_install: False' (e.g. in /etc/iiab/local_vars.yml) WHEN 'kolibri_installed' is defined (e.g. in /etc/iiab/iiab_state.yml) -- IIAB DOES NOT SUPPORT UNINSTALLS -- please verify those 2 files especially, and other places variables are defined?"}

Think this might be an admin-console issue, the tick box uncheck should of only written 'enabled False' and left as 'install True' in local_vars.yml

ubuntu@exclusive-limpkin:/opt/iiab/iiab$ cat adm-run-roles-tmp.yml
```
---
- hosts: all
  become: yes

  vars_files:
  - vars/default_vars.yml
  - vars/{{ ansible_local.local_facts.os_ver }}.yml
  - /etc/iiab/local_vars.yml
  - /etc/iiab/iiab_state.yml

  roles:
    - { role: 0-init }
    - { role: nextcloud }
    - { role: sugarizer }
    - { role: network }
```

_Originally posted by @jvonau in https://github.com/iiab/iiab/issues/3189#issuecomment-1114509740_
