### ISSUE TITLE
Using 'ansible_distribution' to detect host operating system 

### ISSUE THREAD

**Issue by arky** [iiab/iiab#425]
Perhaps using `ansible_distribution` to better way to handle different operating system differences.  

There are some good examples to handle this: 

http://docs.ansible.com/ansible/latest/playbooks_best_practices.html#operating-system-and-distribution-variance

```
- hosts: all
  tasks:
    - include_vars: "os_{{ ansible_distribution }}.yml"
    - debug: var=asdf

```

https://ansible-tips-and-tricks.readthedocs.io/en/latest/os-dependent-tasks/variables/

```
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars
```
