### ISSUE TITLE
Enhancement - Generate Dynamic Playbook - ./runrole instead of ./runtags

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#714]
Give a list of desired tags to run as currently done by runtags, generate a dynamic top level playbook to include the vars section, aggregate 0 [AKA [Stage 0](https://github.com/iiab/iiab/tree/master/roles/0-init)] and the role of each passed tag, assuming that tag name and role name are the same.

**Comment by holta** [comment]
Given that Ansible 2.5 has broken ./runtags (neither #712 nor #716 fully resolve this just yet) @tim-moody is also exploring a possibly much simplified replacement command (`./runrole`, that works quite separately from Ansible's tag system).  Perhaps with /opt/iiab/iiab/iiab-run-one-role.yml along these lines:
```
---
- hosts: all
  become: yes

  vars_files:
  - roles/0-init/defaults/main.yml
  - vars/default_vars.yml
  - vars/{{ ansible_local.local_facts.os_ver }}.yml
  - vars/local_vars.yml

  tasks:

  - name: 0-init
    include_role:
      name: 0-init
    tags: 0-init

  - name: Runtag
    include_role:
      name: {{ run_role }}

ansible-playbook -i ansible_hosts iiab-tmp-run.yml --connection=local -e "run_role=$1"
```
If running multiple roles is important, perhaps something like...
```
ansible-playbook -i ansible_hosts run_roles.yml  --connection=local -e "role_list=kiwix,kalite"
```
List's syntax needs fixing, perhaps...
```
role_list=['kiwix','kalite']
```
If multiple roles are even necessary.  Regardless, our 11 aggregate roles (Stage 0-9 and network) can be invoked, using `./runrole 7-edu-apps` etc.
