### ISSUE TITLE
apache2: Ansible src option requires state to be 'link' or 'hard' (not 'absent')

### ISSUE THREAD

**Issue by holta** [iiab/iiab#860]
Ansible 2.6.0 warns us about flawed code:
```
TASK [httpd : Remove the default apache2 config file (debuntu)] ****************
 [WARNING]: The src option requires state to be 'link' or 'hard'.  This will
become an error in Ansible 2.10
```
Thanks all for addressing this ([Line 53-58 of roles/httpd/tasks/main.yml](https://github.com/iiab/iiab/blob/master/roles/httpd/tasks/main.yml#L53-L58)) those who have Apache/Nginx expertise and those who can!

**Comment by holta** [comment]
Regardless what version Ansible, the "src" line ([Line 56](https://github.com/iiab/iiab/blob/master/roles/httpd/tasks/main.yml#L56)) looks like a bug &mdash; was is included for the purposes of deleting /etc/apache2/sites-available/000-default.conf ?
```
- name: Remove the default apache2 config file (debuntu)
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    src: /etc/apache2/sites-available/000-default.conf
    state: absent
  when: is_debuntu
```
FWIW the official syntax for Ansible's file module is:
https://docs.ansible.com/ansible/latest/modules/file_module.html
